# Generated by Django 3.2.6 on 2021-08-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('animal_type', models.CharField(choices=[('DG', 'Dog'), ('CT', 'Cat'), ('HR', 'Horse')], max_length=2)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('speciality', models.CharField(choices=[('SM', 'Small pets'), ('LG', 'Large pets'), ('AN', 'Antesthesia')], max_length=2)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('pets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('timeslot', models.IntegerField(choices=[(0, '09:00 - 09:30'), (1, '09:30 - 10:00'), (2, '10:00 - 10:30'), (3, '10:30 - 11:00'), (4, '11:00 - 11:30'), (5, '11:30 - 12:00'), (6, '12:00 - 12:30'), (7, '12:30 - 13:00'), (8, '13:00 - 13:30'), (9, '13:30 - 14:00'), (10, '14:00 - 14:30'), (11, '14:30 - 15:00'), (12, '15:00 - 15:30'), (13, '15:30 - 16:00'), (14, '16:00 - 16:30'), (15, '16:30 - 17:00')])),
                ('notes', models.CharField(blank=True, max_length=1500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.physician')),
            ],
            options={
                'unique_together': {('physician', 'date', 'timeslot')},
            },
        ),
    ]
